modLoader="javafml"
loaderVersion="[36,)"
license="All rights reserved"

[[mods]]

itemIcon="rigoranthusemortisreborn:assets/ftbchunks/textures/faces/rigoranthusemortisreborn/canis_chordata.png"

modId="rigoranthusemortisreborn"

version="2.0.0"

Manifest-Version="1.0"
Implementation-Title="machiavellian-modness"
Implementation-Version="1.0.0"

displayName="Rigoranthus Emortis Reborn"

logoFile="rigoranthus_emortis_logo.png"

displayURL="https://www.curseforge.com/members/platinumg17/projects"

credits="Audio sourced from: Zapsplat.com (Little Robot Sound Factory, 344 Audio, Zapsplat), orangefreesounds.com, fesliyanstudios.com, quicksounds.com"

authors="PlatinumG17"

description='''
Adds unique and Nasty Mobs & a Pet with a 3 stage Evolution Line! 
What more could you want?

Additionally, this mod adds a number of:
    - Tools & Resources
    - Weapons & Armor-sets
    - Decorative Blocks
'''

[[dependencies.rigoranthusemortisreborn]]
modId="forge"
mandatory=true
versionRange="[36,)"
ordering="NONE"
side="BOTH"

[[dependencies.rigoranthusemortisreborn]]
modId="minecraft"
mandatory=true
versionRange="[1.16.5, 1.17.1]"
ordering="NONE"
side="BOTH"

[[dependencies.rigoranthusemortisreborn]]
modId="jei"
mandatory=false
versionRange="[7,)"
ordering="NONE"
side="BOTH"

[[dependencies.rigoranthusemortisreborn]]
modId="ftbguilibrary"
mandatory=false
versionRange="[1,)"
ordering="NONE"
side="BOTH"

[[dependencies.rigoranthusemortisreborn]]
modId="alltheores"
mandatory=false
versionRange="[1.3.6,)"
ordering="NONE"
side="BOTH"

[[dependencies.rigoranthusemortisreborn]]
modId="pmmo"
mandatory=false
versionRange="[1.16.5-3,)"
ordering="NONE"
side="BOTH"

[[dependencies.rigoranthusemortisreborn]]
modId="geckolib3"
mandatory=true
versionRange="[geckolib-forge-1.16.5:3.0.33,)"
ordering="AFTER"
side="BOTH"

#[[dependencies.rigoranthusemortisreborn]]
#modId="abnormals_core"
#mandatory=true
#versionRange="[3.1.0,)"
#ordering="AFTER"
#side="BOTH"

[[dependencies.rigoranthusemortisreborn]]
modId="libx"
mandatory=false
versionRange="[1.16.3-1.0.76,)"
ordering="NONE"
side="BOTH"