modLoader="javafml"
loaderVersion="[36,)"
license="GNU GENERAL PUBLIC LICENSE"

[[mods]]
    modId="rigoranthusemortisreborn"
    version="${version}"
    logoFile="rigoranthus_emortis_logo.png"
    itemIcon="rigoranthusemortisreborn:assets/ftbchunks/textures/faces/rigoranthusemortisreborn/canis_chordata.png"
    configBackground = "rigoranthusemortisreborn:textures/gui/advancements/azuloreal.png"
    authors="PlatinumG17 (aka Matt)"
    credits="Some code inspired by or sourced from: Percivalalb, Baileyholl & XenoMustache.\n Audio sourced from: Zapsplat, Orangefreesounds, Fesliyanstudios, & Quicksounds"
    displayURL="https://www.curseforge.com/members/platinumg17/projects"
    displayName=" Rigoranthus Emortis Reborn"
description='''
Adds unique and Nasty Mobs & a Pet with a 3 stage Evolution Line! 
What more could you want?

Additionally, this mod adds a number of:
    - Tools & Resources
    - Weapons & Armor-sets
    - Decorative Blocks
'''

[[dependencies.rigoranthusemortisreborn]]
modId="minecraft"
mandatory=true
versionRange="[1.16.5,)"
ordering="NONE"
side="BOTH"

[[dependencies.rigoranthusemortisreborn]]
modId="forge"
mandatory=true
versionRange="[36.2.0,)"
ordering="NONE"
side="BOTH"

[[dependencies.rigoranthusemortisreborn]]
modId="geckolib3"
mandatory=true
versionRange="[geckolib-forge-1.16.5:3.0.33,)"
ordering="AFTER"
side="BOTH"

[[dependencies.rigoranthusemortisreborn]]
modId="curios"
mandatory=true
versionRange="[1.16.3-4.0.1.0,)"
ordering="AFTER"
side="BOTH"

[[dependencies.rigoranthusemortisreborn]]
modId="abnormals_core"
mandatory=true
versionRange="[3.2.0,)"
ordering="AFTER"
side="BOTH"

[[dependencies.rigoranthusemortisreborn]]
modId="patchouli"
mandatory=true
versionRange="[1.16-42,)"
ordering="AFTER"
side="BOTH"

[[dependencies.rigoranthusemortisreborn]]
modId="jei"
mandatory=false
versionRange="[7,)"
ordering="NONE"
side="BOTH"

[[dependencies.rigoranthusemortisreborn]]
modId="ftbguilibrary"
mandatory=false
versionRange="[1,)"
ordering="NONE"
side="BOTH"

[[dependencies.rigoranthusemortisreborn]]
modId="alltheores"
mandatory=false
versionRange="[1.3.6,)"
ordering="NONE"
side="BOTH"

[[dependencies.rigoranthusemortisreborn]]
modId="pmmo"
mandatory=false
versionRange="[1.16.5-3,)"
ordering="NONE"
side="BOTH"

[[dependencies.rigoranthusemortisreborn]]
modId="libx"
mandatory=false
versionRange="[1.16.3-1.0.76,)"
ordering="NONE"
side="BOTH"